#!/bin/bash

echo "Required Environment Variables for Vercel:"
echo ""
echo "You already have:"
echo "✅ DATABASE_URL"
echo "✅ DIRECT_URL"
echo "✅ SESSION_SECRET_KEY"
echo "✅ ENVIRONMENT"
echo ""
echo "Missing Variables - Add these in Vercel Dashboard:"
echo ""
echo "1. NEXT_PUBLIC_API_URL"
echo "   Value: https://diffit-tools.vercel.app"
echo "   (or your custom domain if you have one)"
echo ""
echo "2. NODE_ENV"
echo "   Value: production"
echo ""
echo "Optional but recommended:"
echo ""
echo "3. ENABLE_WASM_DIFF"
echo "   Value: true"
echo ""
echo "4. MAX_FILE_SIZE_MB"
echo "   Value: 10"
echo ""
echo "5. RATE_LIMIT_ENABLED"
echo "   Value: true"