[package]
name = "diffit-diff-engine"
version = "2.0.0"
authors = ["Diffit Tools Team"]
edition = "2021"
description = "High-performance WebAssembly diff engine for diffit.tools"
license = "MIT"
repository = "https://github.com/diffit-tools/diffit-v2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
js-sys = "0.3.72"
web-sys = { version = "0.3.72", features = [
    "console",
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "Performance"
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
console_error_panic_hook = { version = "0.1.7", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
once_cell = "1.20"
lazy_static = "1.5"
regex = "1.11"
aho-corasick = "1.1"
memchr = "2.7"
bstr = "1.10"
parking_lot = "0.12"
rustc-hash = "2.0"
smallvec = "1.13"

[dev-dependencies]
wasm-bindgen-test = "0.3.45"
criterion = "0.5"
proptest = "1.5"
similar = "2.6"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[features]
default = ["console_error_panic_hook"]
wee_alloc = ["dep:wee_alloc"]

[[bench]]
name = "diff_benchmarks"
harness = false